### ISSUE TITLE
jaxlib on jetson

### ISSUE THREAD

**Issue by christhechris** [TolimanSpace/toliman-flake#2]
### usefull links
https://docs.nvidia.com/cuda/cuda-for-tegra-appnote/index.html#from-network-repositories-or-local-installers
https://github.com/google/jax
https://forums.developer.nvidia.com/t/jax-on-jetson-nano/182593

### notes
- jax can be built on Jetson, but latest version requires at least Cuda 11.8 or 12 (11.4 is part of Jetpack 5.1; https://www.stereolabs.com/blog/nvidia-jetson-l4t-and-jetpack-support)
- CUDA can be updated see above, but would also need to do upgrade on nix part as well
- older version of Jax could be used maybe as alternative, trying [jax-v0.4.13](https://github.com/google/jax/tree/jax-v0.4.13) now

**Comment by christhechris** [comment]
working through some errors: https://chat.openai.com/share/97c3be3b-8753-4c48-9c8c-68f684a69ff0

**Comment by christhechris** [comment]
proper build cmd python3 build/build.py --enable_cuda --cuda_compute_capabilities compute_72 --cuda_path=$CUDA_HOME --cudnn_path=$CUDNN_HOME

Finally gives cuda version error as build fail reason `jaxlib/cuda/versions_helpers.cc:27:2: error: #error "JAX requires CUDA 11.8 or newer."`

**Comment by christhechris** [comment]
nope https://github.com/google/jax/blob/main/CHANGELOG.md#jax-048-march-29-2023 11.4 was dropped earlier then flux required version.  Jax 0.4.13+

**Comment by arduano** [comment]
Some things to note: 

The way anduril packaged cuda is very non-standard relative to the way nixpkgs does it, so many assumptions are broken, and I had to make a big hack to fix it over in the shared overlay file. This is because Nvidia doesn't actually provide a portable SDK, especially one you can compile, instead it just provides some raw .deb files for the Jetson.

Also, one of the best ways of testing if the environment is applied correctly is to use the jax-test python executable that Connor and I made, and run commands inside there to query the environment. Nix doesn't have global state generally (except for system level stuff like the kernel and gpu drivers), so it's difficult to know what's going on inside a derivation without just getting the code that's running in the derivation to tell you

However, things like nvidia-smi should be functional globally, so if they're not then that could be a symptom of other issues too.

**Comment by christhechris** [comment]
can cuda part of the global state?

**Comment by arduano** [comment]
Yes, but that technically goes against Nix principles, though if it works then it works. I'm not sure how to make cuda part of global state, maybe you need to set some environment variables? Shouldn't be too hard if that's the case: https://nixos.wiki/wiki/Environment_variables

**Comment by christhechris** [comment]
all good. going to focus for the moment on getting jax working on normal JetPack 5.1.3 LT4 35.1 system, get wheels built etc. and go from there for now.

**Comment by christhechris** [comment]
final found correct way to update cuda https://developer.nvidia.com/cuda-12-2-0-download-archive?target_os=Linux&target_arch=aarch64-jetson&Compilation=Native&Distribution=Ubuntu&target_version=20.04&target_type=deb_network

**Comment by CLangford2098** [comment]
Encountering a new issue now. Have a similar issue to this: https://github.com/google/jax/issues/5723.

Seems like a driver and CUDA version incompatibility. Will investigate further

Cuda version: 12.2.140
Driver version: 35.5.0 (running `grep "X Driver" /var/log/Xorg.0.log`)

**Comment by christhechris** [comment]
Can you share your error
________________________________

**Comment by CLangford2098** [comment]
`E0318 11:57:21.693717    5506 pjrt_stream_executor_client.cc:2813] Execution of replica 0 failed: INTERNAL: CustomCall failed: jaxlib/gpu/prng_kernels.cc:33: operation gpuGetLastError() failed: no kernel image is available for execution on the device
jax.errors.SimplifiedTraceback: For simplicity, JAX has removed its internal frames from the traceback of the following exception. Set JAX_TRACEBACK_FILTERING=off to include these.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/toliman/jax/jax/_src/random.py", line 711, in normal
    return _normal(key, shape, dtype)  # type: ignore
jaxlib.xla_extension.XlaRuntimeError: INTERNAL: CustomCall failed: jaxlib/gpu/prng_kernels.cc:33: operation gpuGetLastError() failed: no kernel image is available for execution on the device`

Running the "Multiplying Matrices" Code from here: https://jax.readthedocs.io/en/latest/notebooks/quickstart.html

**Comment by CLangford2098** [comment]
I've just added the versions to my initial comment. I'm concerned about the driver version.
_"We recommend installing the newest driver available from NVIDIA, but the driver must be version >= 525.60.13 for CUDA 12 and >= 450.80.02 for CUDA 11 on Linux."_
I tried installing driver version 535 but I don't think it's using that (and I think the installation didn't work)

**Comment by christhechris** [comment]
fix was to specify compute mode, `python3 build/build.py --enable_cuda --cuda_compute_capabilities=sm_72'
